api/urls.py
from django.urls import path
from .views import BookReviewDetailAPIView , BookReviewListAPIView

# from rest_framework.routers import DefaultRouter
# from .views import BookReviewViewSet
app_name = 'api'
#
# router = DefaultRouter()
# router.register('reviews', BookReviewViewSet, basename='review')
# urlpatterns = router.urls


urlpatterns = [
    path('reviews/' , BookReviewListAPIView.as_view() , name='books_reviews_api'),
    path('reviews/<int:pk>/' , BookReviewDetailAPIView.as_view() , name='review_detail_api'),
]

books/urls.py
from django.urls import path
from .views import BookListView , BookDetailView , AddReviewView , EditReviewView , ConfirmDeleteReview , DeleteView , GenreView

app_name = "books"
urlpatterns = [
    path('' , BookListView.as_view() , name="books_list"),
    path('<int:pk>/' , BookDetailView.as_view() , name="books_detail"),
    path('<int:pk>/review/' , AddReviewView.as_view() , name="books_reviews"),
    path('<int:book_id>/reviews/<int:review_id>/edit/' , EditReviewView.as_view() , name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/confirm/' , ConfirmDeleteReview.as_view() , name='confirm_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/' , DeleteView.as_view() , name='delete_review'),
    path('genre/' , GenreView.as_view() , name='genres_list'),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from .views import home_page , landing_page
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Books List Api",
        default_version='v1',
        description="Goodreads  New Project",
        terms_of_service="demo.com",
        contact=openapi.Contact(email='xurramovotabek568@gmail.com'),
        license=openapi.License(name="demo license"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny ,]
)



urlpatterns = ([
    path('admin/', admin.site.urls),
    path('' ,landing_page , name="landing_page"),
    path('home/' , home_page , name="home_page"),
    path('users/' , include('users.urls') , name="users"),
    path('books/' , include('books.urls') , name="books"),
    path('api/v1/' , include('api.urls') , name="api"),
    path('api-auth/' , include('rest_framework.urls')),
    path('api/v1/dj-rest-auth/' , include('dj_rest_auth.urls')),
        path('api/v1/dj-rest-auth/registration/' , include('dj_rest_auth.registration.urls')),
        # swagger
        path('swagger/' , schema_view.with_ui(
            'swagger' , cache_timeout=0) , name='schema-swagger-ui'),
        path('redoc/' , schema_view.with_ui(
            'redoc' , cache_timeout=0) , name='schema-redoc-ui'),
])+static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

books/models.py
from django.utils import timezone

from users.models import CustomUser
from django.core.validators import MinValueValidator , MaxValueValidator
from django.db import models

# Create your models here.

class Genre(models.Model):
    genre_name = models.CharField(max_length=200)
    genre_slug = models.CharField(max_length=200)

    def __str__(self):
        return self.genre_name
class Book(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    language = models.CharField(max_length=200)
    page_count = models.IntegerField()
    genre = models.ForeignKey(Genre,on_delete=models.CASCADE)
    cover_picture = models.ImageField(default="default_cover.jpg" ,upload_to='books_image')

    def __str__(self):
        return self.title


class Author(models.Model):
    username = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    born = models.CharField(max_length=200)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

class BookAuthor(models.Model):
    book = models.ForeignKey(Book , on_delete=models.CASCADE)
    author = models.ForeignKey(Author , on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.book} - {self.author}"



class BookReview(models.Model):
    user = models.ForeignKey(CustomUser , on_delete=models.CASCADE)
    book = models.ForeignKey(Book , on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1) , MaxValueValidator(5)]
    )

    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment[:200]

books/forms.py
from django import forms

from .models import BookReview

class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1 , max_value=5)
    class Meta:
        model = BookReview
        fields = ('stars_given' , 'comment')

books/views.py
from itertools import count

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
# from django.views.generic import ListView , DetailView
from .forms import BookReviewForm
from .models import Book, BookReview, Genre
from users.models import CustomUser
# Create your views here.


# class BookListView(ListView):
#     template_name = 'books/list.html'
#     queryset = Book.objects.all()
#     context_object_name = "books"
#     paginate_by = 5


class BookListView(View):
    def get(self , request):
        books = Book.objects.all().order_by("pk")
        search_query = request.GET.get('q' , '')
        if search_query:
            books = books.filter(title__icontains=search_query)

        page_size = request.GET.get('page_size' , 5)
        paginator = Paginator(books , page_size)

        page_num = request.GET.get('page' ,1)
        page_obj = paginator.get_page(page_num)

        context = {
            "page_obj":page_obj,
            "search_query":search_query,
        }
        return render(request , 'books/list.html' , context)


# class BookDetailView(DetailView):
#     template_name = 'books/views.html'
#     queryset = Book.objects.all()
#     context_object_name = "book"


class BookDetailView(View):
    def get(self , request , pk):
        book = Book.objects.get(pk=pk)
        review_form = BookReviewForm()

        review_all = book.bookreview_set.all()
        sum = 0
        for i in review_all:
            sum+=i.stars_given

        review_count = review_all.count()
        if review_count > 0:
            rating = round(sum/review_count)

        else:
            rating = 0

        rating_full = [x for x in range(rating)]
        rating_empty = [x for x in range(5-rating)]

        context = {
            "book":book,
            "review_form":review_form,
            "rating":rating,
            "rating_full":rating_full,
            "rating_empty":rating_empty,
        }

        return render(request , "books/views.html" , context)


class AddReviewView(LoginRequiredMixin ,View):
    def post(self , request , pk):
        book = Book.objects.get(pk=pk)
        review_form = BookReviewForm(data=request.POST)
        context = {
            "book": book,
            "review_form": review_form,
        }

        if review_form.is_valid():
            BookReview.objects.create(
                book = book,
                user = request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment = review_form.cleaned_data['comment']
            )
            return redirect(reverse("books:books_detail",kwargs={"pk":book.pk}))

        return render(request, "books/views.html", context)

class EditReviewView(LoginRequiredMixin , View):
    def get(self , request , book_id , review_id):
        book = Book.objects.get(pk=book_id)
        review = book.bookreview_set.get(pk=review_id)
        review_form = BookReviewForm(instance=review)
        context = {
            "book":book,
            "review":review,
            "review_form": review_form,
        }
        return render(request , 'books/edit_review.html' , context)

    def post(self , request , book_id , review_id):
        book = Book.objects.get(pk=book_id)
        review = book.bookreview_set.get(pk=review_id)
        review_form = BookReviewForm(instance=review , data=request.POST)

        if review_form.is_valid():
            review_form.save()

            return redirect(reverse("books:books_detail", kwargs={"pk": book.pk}))

        context = {
            "book": book,
            "review": review,
            "review_form": review_form,
        }

        return render(request, 'books/edit_review.html', context)


class ConfirmDeleteReview(LoginRequiredMixin , View):
    def get(self , request , book_id , review_id):
        books = Book.objects.all().order_by("pk")
        book = Book.objects.get(pk=book_id)
        review = book.bookreview_set.get(pk=review_id)

        context = {
            "books":books,
            "book": book,
            "review": review,
        }
        return render(request , 'books/confirm_delete.html' ,context)

class DeleteView(LoginRequiredMixin , View):
    def get(self , request , book_id , review_id):
        book = Book.objects.get(pk=book_id)
        review = book.bookreview_set.get(pk=review_id)

        review.delete()
        messages.success(request , "You have successfully deleted this review")

        return redirect(reverse("books:books_detail", kwargs={"pk": book.pk}))

class GenreView(LoginRequiredMixin , View):
    def get(self , request):
        genre_list = Genre.objects.all()
        context = {
            "genre_list": genre_list,
        }

        return render(request , 'books/genre.html' ,context)

templates/books/confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Confirm Delete Review{% endblock %}
{% block content %}
    <h2>Are you sure you want to delete this review ?</h2>
    <hr>
    <div class="col-md-6">
        <h4 class="font-monospace"><b>Book title : </b><a href="{% url 'books:books_detail' book.pk %}">{{ book.title }}</a></h4>
    </div>
    <div>
        <h5 class="font-monospace"><b>Comment : </b> {{ review.comment }}</h5>
    </div>

    <a href="{% url 'books:delete_review' book.pk review.pk %}"><button class="btn btn-outline-success">Yes</button></a>
    <a href="{% url 'books:books_detail' book.pk %}"><button class="btn btn-outline-danger">No</button></a>
{% endblock %}

templates/books/edit_review.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Edit Review{% endblock %}
{% block content %}
    <div class="row mb-4">
        <h2>Edit Review</h2>
        <div class="col-md-8">
            <div class="container">
                    <div class="col-md-10 mx-5">
                        <form method="post" action="{% url 'books:edit_review' book.pk review.pk %}">{% csrf_token%}
                            {{ review_form | crispy }}
                            <button type="submit" class="btn btn-success">Save</button>
                        </form>
                    </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/books/genre.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Genre List Page{% endblock %}
{% block content %}
    <div class="container">
         <div class="rows">
             <div class="col-6">
                 <ol>
                     {% for genre in genre_list %}
                     <li class="font-monospace"><a href="{% url 'books:genres_list' %}">{{ genre }}</a></li>
                     {% endfor %}
                 </ol>
             </div>
         </div>
    </div>
{% endblock %}

templates/books/list.html
{% extends 'base.html' %}
{% block title %}Books Page{% endblock %}
{% block content %}
<h2>Books</h2>
    <div class="row">
        {% if page_obj %}
                {% for i in page_obj.object_list %}
                    <div class="col-md-4">
                        <img class="book_size" alt="cover book picture" src="{{ i.cover_picture.url }}">
                    </div>
                    <div class="col-md-8">
                        <h3><a href="{% url 'books:books_detail' i.pk %}">{{ i.title }}</a></h3>
                        <p>{{ i.description }}</p>
                    </div>
                    <hr>
                {% endfor %}
                <nav aria-label="Page navigation example">
                  <ul class="pagination">
                    <li class="page-item">
                      {% if page_obj.has_previous %}
                      <a class="page-link" href="{% url 'books:books_list' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                      {% endif %}
                    </li>
                    {% if  page_obj.number > 1 %}
                        <li class="page-item">
                            {% if page_obj.has_previous %}
                            <a class="page-link" href="{% url 'books:books_list' %}?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                            {% endif %}
                        </li>
                    {% endif %}
                    <li class="page-item active"><a class="page-link" href="">{{ page_obj.number }}</a></li>
                    <li class="page-item">
                        {% if page_obj.has_next %}
                            <a class="page-link" href="{% url 'books:books_list' %}?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
                        {% endif %} </li>
                    <li class="page-item">
                      {% if page_obj.has_next %}
                      <a class="page-link" href="{% url 'books:books_list' %}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                      {% endif %}
                    </li>
                  </ul>
                </nav>
        {% else %}
            No books found.
        {% endif %}
    </div>
    

{% endblock %}

templates/books/views.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Books Page{% endblock %}
{% block content %}
<h1>Book</h1>
    <div class="row">
        <div class="col-md-4">
            <img class="book_size" alt="default book picture" src="{{ book.cover_picture.url }}">
            <h6 class="mt-4">ISBN  : {{ book.isbn }}</h6>
            <p>Language : {{ book.language }}  /  Page count : {{ book.page_count }}</p>
            <p>Rating :
                {% for i in rating_full %}
                    <i class="bi bi-star-fill"></i>
                {% endfor %}
                {% for n in  rating_empty %}
                    <i class="bi bi-star"></i>
                {% endfor %}
            </p>
        </div>
        <div class="col-md-8">
            <h2>{{ book.title }}</h2>
            <h5 class="fst-italic">Autored by {% for book_author in book.bookauthor_set.all %}
                                 {{ book_author.author.full_name }}
                             {% endfor %}
            </h5><br>
            <p>{{ book.description }}</p>
        </div>
    </div>
    <hr>
    <div class="row mb-4">
        <div class="col-md-8">
            <div class="container">
                    <div class="col-md-10 mx-5">
                        <form method="post" action="{% url 'books:books_reviews' book.pk %}">{% csrf_token%}
                            {{ review_form | crispy }}
                            <button type="submit" class="btn btn-success">Add review</button>
                        </form>
                    </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col">
        {% if book.bookreview_set.exists %}
            <h3>Ratings & Reviews</h3><hr>
        {% endif %}
            {% for review in book.bookreview_set.all %}
                <div class="container">
                    <div class="col-md-10 mx-5">
                        <h4><img style="height: 50px ; width: 50px; border-radius: 50%"  class="mx-2" alt="profile review photo" src="{{ review.user.profile_picture.url }}">{{ review.user.username }}  rated it {{ review.stars_given }}  stars  / <span class="fw-lighter">date : {{ review.created_at }}  / </span>
                        {% if review.user == request.user %}
                            <a href="{% url 'books:edit_review' book.pk review.pk %}"><i class="bi bi-pencil-square"></i></a>
                            <a href="{% url 'books:confirm_review' book.pk review.pk %}"><i class="bi bi-trash"></i></a>
                        {% endif %}
                        </h4>
                        <p class="font-monospace">{{ review.comment }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}