api/urls.py
from django.urls import path
from .views import BookReviewDetailAPIView , BookReviewListAPIView

# from rest_framework.routers import DefaultRouter
# from .views import BookReviewViewSet
app_name = 'api'
#
# router = DefaultRouter()
# router.register('reviews', BookReviewViewSet, basename='review')
# urlpatterns = router.urls


urlpatterns = [
    path('reviews/' , BookReviewListAPIView.as_view() , name='books_reviews_api'),
    path('reviews/<int:pk>/' , BookReviewDetailAPIView.as_view() , name='review_detail_api'),
]

books/urls.py
from django.urls import path
from .views import BookListView , BookDetailView , AddReviewView , EditReviewView , ConfirmDeleteReview , DeleteView , GenreView

app_name = "books"
urlpatterns = [
    path('' , BookListView.as_view() , name="books_list"),
    path('<int:pk>/' , BookDetailView.as_view() , name="books_detail"),
    path('<int:pk>/review/' , AddReviewView.as_view() , name="books_reviews"),
    path('<int:book_id>/reviews/<int:review_id>/edit/' , EditReviewView.as_view() , name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/confirm/' , ConfirmDeleteReview.as_view() , name='confirm_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/' , DeleteView.as_view() , name='delete_review'),
    path('genre/' , GenreView.as_view() , name='genres_list'),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from .views import home_page , landing_page
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Books List Api",
        default_version='v1',
        description="Goodreads  New Project",
        terms_of_service="demo.com",
        contact=openapi.Contact(email='xurramovotabek568@gmail.com'),
        license=openapi.License(name="demo license"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny ,]
)



urlpatterns = ([
    path('admin/', admin.site.urls),
    path('' ,landing_page , name="landing_page"),
    path('home/' , home_page , name="home_page"),
    path('users/' , include('users.urls') , name="users"),
    path('books/' , include('books.urls') , name="books"),
    path('api/v1/' , include('api.urls') , name="api"),
    path('api-auth/' , include('rest_framework.urls')),
    path('api/v1/dj-rest-auth/' , include('dj_rest_auth.urls')),
        path('api/v1/dj-rest-auth/registration/' , include('dj_rest_auth.registration.urls')),
        # swagger
        path('swagger/' , schema_view.with_ui(
            'swagger' , cache_timeout=0) , name='schema-swagger-ui'),
        path('redoc/' , schema_view.with_ui(
            'redoc' , cache_timeout=0) , name='schema-redoc-ui'),
])+static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView , LoginView , ProfileView , LogoutView , ProfileUpdateView


app_name = "users"
urlpatterns = [
    path('register/' , RegisterView.as_view() , name='register'),
    path('login/' ,LoginView.as_view() , name='login'),
    path('logout/' , LogoutView.as_view() ,name='logout'),
    path('profile/' , ProfileView.as_view() ,name="profile"),
    path('profile/edit/' , ProfileUpdateView.as_view() , name="profile_edit"),
]

templates/base.html
<!DOCTYPE html>
{% url 'books:books_list' as books_list_url %}
{% url 'home_page' as home_page_url %}
{% url 'books:genres_list' as genre_page_url %}
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads Clone {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/users/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/books/book_info.css' %}">
    <link rel="stylesheet" href="{% static 'css/books/review.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body class="mx-4 ">
<nav class="navbar navbar-expand-lg mb-3 navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads Clone</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == books_list_url %} active {% endif %}" aria-current="page" href="{{ books_list_url }}">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == genre_page_url %} active {% endif %}" aria-current="page" href="{{ genre_page_url }}">Genre</a>
        </li>
      </ul>
        <div class="mx-5">
            <form class="d-flex mx-5" method="get">
               <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ search_query }}">
               <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        <div class="me-4">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle btn btn-outline-success" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ request.user.username }}
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                      </ul>
                </li>
                </ul>
            {% else %}
                <a class="btn btn-outline-success" href="{% url 'users:login' %}">Login</a>
            {% endif %}

        </div>
    </div>
  </div>
</nav>
<div class="container">
    {% if messages %}
        <div class="mt-2">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{  message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}

    {% block content %} {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block content %}
<div class="container">
    <h1 class="mb-4">Goodreads Clone</h1>
    <div class="row">
        {% if page_object %}
                {% for review in page_object.object_list %}
                    <div class="col-md-3">
                        <a href="{% url 'books:books_detail' review.book.pk %}"><img class="book_review_picture center" alt="book review photo" src="{{ review.book.cover_picture.url }}"></a>
                    </div>
                    <div class="col-md-8">
                        <h4><img style="height: 50px ; width: 50px; border-radius: 50%"  class="mx-2" alt="profile review photo" src="{{ review.user.profile_picture.url }}">{{ review.user.username }}  rated it {{ review.stars_given }}  stars  / <span class="fw-lighter">{{ review.created_at | date:"M d, Y" }}</span></h4>
                        <p>{{ review | truncatechars:300 }}</p>
                    </div>
                    <hr>
                {% endfor %}
                <nav aria-label="Page navigation example">
                  <ul class="pagination">
                    <li class="page-item">
                      {% if page_object.has_previous %}
                      <a class="page-link" href="{% url 'home_page' %}?page={{ page_object.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                      {% endif %}
                    </li>
                    {% if  page_object.number > 1 %}
                        <li class="page-item">
                            {% if page_object.has_previous %}
                            <a class="page-link" href="{% url 'home_page' %}?page={{ page_object.previous_page_number }}">{{ page_object.previous_page_number }}</a>
                            {% endif %}
                        </li>
                    {% endif %}
                    <li class="page-item active"><a class="page-link" href="">{{ page_object.number }}</a></li>
                    <li class="page-item">
                        {% if page_object.has_next %}
                            <a class="page-link" href="{% url 'home_page' %}?page={{ page_object.next_page_number }}">{{ page_object.next_page_number }}</a>
                        {% endif %} </li>
                    <li class="page-item">
                      {% if page_object.has_next %}
                      <a class="page-link" href="{% url 'home_page' %}?page={{ page_object.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                      {% endif %}
                    </li>
                  </ul>
                </nav>
        {% else %}
            No reviews found.
        {% endif %}
    </div>
</div>
{% endblock %}

templates/landing_page.html
{% extends 'base.html' %}
{% block title %}Goodreads Clone{% endblock %}
{% block content %}
    <div class="row mb-4">
        <div class="col">
            <h2>Goodreads Clone</h2>
            <div class="container">
                    <div class="col mx-5">
                        <p>
                            Goodreads is an American social cataloging website and a subsidiary of Amazon that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.

                            Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler. In December 2007, the site had 650,000 members and 10,000,000 books had been added. By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees. On March 28, 2013, Amazon announced its acquisition of Goodreads, and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.

                            By July 2019, the site had 90 million members.
                        </p>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}