api/urls.py
from django.urls import path
from .views import BookReviewDetailAPIView , BookReviewListAPIView

# from rest_framework.routers import DefaultRouter
# from .views import BookReviewViewSet
app_name = 'api'
#
# router = DefaultRouter()
# router.register('reviews', BookReviewViewSet, basename='review')
# urlpatterns = router.urls


urlpatterns = [
    path('reviews/' , BookReviewListAPIView.as_view() , name='books_reviews_api'),
    path('reviews/<int:pk>/' , BookReviewDetailAPIView.as_view() , name='review_detail_api'),
]

books/urls.py
from django.urls import path
from .views import BookListView , BookDetailView , AddReviewView , EditReviewView , ConfirmDeleteReview , DeleteView , GenreView

app_name = "books"
urlpatterns = [
    path('' , BookListView.as_view() , name="books_list"),
    path('<int:pk>/' , BookDetailView.as_view() , name="books_detail"),
    path('<int:pk>/review/' , AddReviewView.as_view() , name="books_reviews"),
    path('<int:book_id>/reviews/<int:review_id>/edit/' , EditReviewView.as_view() , name='edit_review'),
    path('<int:book_id>/reviews/<int:review_id>/confirm/' , ConfirmDeleteReview.as_view() , name='confirm_review'),
    path('<int:book_id>/reviews/<int:review_id>/delete/' , DeleteView.as_view() , name='delete_review'),
    path('genre/' , GenreView.as_view() , name='genres_list'),
]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path , include
from .views import home_page , landing_page
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Books List Api",
        default_version='v1',
        description="Goodreads  New Project",
        terms_of_service="demo.com",
        contact=openapi.Contact(email='xurramovotabek568@gmail.com'),
        license=openapi.License(name="demo license"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny ,]
)



urlpatterns = ([
    path('admin/', admin.site.urls),
    path('' ,landing_page , name="landing_page"),
    path('home/' , home_page , name="home_page"),
    path('users/' , include('users.urls') , name="users"),
    path('books/' , include('books.urls') , name="books"),
    path('api/v1/' , include('api.urls') , name="api"),
    path('api-auth/' , include('rest_framework.urls')),
    path('api/v1/dj-rest-auth/' , include('dj_rest_auth.urls')),
        path('api/v1/dj-rest-auth/registration/' , include('dj_rest_auth.registration.urls')),
        # swagger
        path('swagger/' , schema_view.with_ui(
            'swagger' , cache_timeout=0) , name='schema-swagger-ui'),
        path('redoc/' , schema_view.with_ui(
            'redoc' , cache_timeout=0) , name='schema-redoc-ui'),
])+static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView , LoginView , ProfileView , LogoutView , ProfileUpdateView


app_name = "users"
urlpatterns = [
    path('register/' , RegisterView.as_view() , name='register'),
    path('login/' ,LoginView.as_view() , name='login'),
    path('logout/' , LogoutView.as_view() ,name='logout'),
    path('profile/' , ProfileView.as_view() ,name="profile"),
    path('profile/edit/' , ProfileUpdateView.as_view() , name="profile_edit"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="profile_default_picture.jpg", upload_to='profile_image')


    def save(self, *args, **kwargs):
        super().save()

users/forms.py
from django import forms

from users.models import CustomUser


"""class UserCreateForm(forms.Form):
    username = forms.CharField(max_length=250)
    first_name = forms.CharField(max_length=200)
    last_name = forms.CharField(max_length=200)
    email = forms.EmailField()
    password = forms.CharField(max_length=128)


    def save(self):
        username = self.changed_data['username']
        first_name = self.changed_data['first_name']
        last_name = self.changed_data['last_name']
        email = self.changed_data['email']
        password = self.changed_data['password']

        user = User.objects.create(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=email,
        )

        user.set_password(password)
        user.save()

        return user"""

class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ("username" , "first_name" , "last_name" , "email" , "password")

    def save(self , commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])

        user.save()

        return user

# class UserLoginForm(forms.Form):
#
#     username = forms.CharField(max_length=200)
#     password = forms.CharField(max_length=128)
#
#     # def clean(self):
#     #     username = self.cleaned_data['username']
#     #     password = self.cleaned_data['password']

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('profile_picture','username' , 'first_name' , 'last_name' , 'email')

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from .forms import UserCreateForm , ProfileEditForm
# Create your views here.

class RegisterView(View):
    def get(self , request):
        create_form = UserCreateForm()
        context = {
            "form":create_form,
        }
        return render(request , 'users/register.html' , context)

    def post(self , request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect("users:login")
        else:
            context = {
                "form":create_form,
            }
            return render(request , 'users/register.html' , context)



class LoginView(View):
    def get(self , request):
        login_form = AuthenticationForm()
        context = {
            "login_form":login_form,
        }
        return render(request , 'users/login.html' , context)

    def post(self , request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request , user)

            messages.success(request , "You have successfully logged in.")

            return redirect("books:books_list")
        else:
            
            context = {
                "login_form":login_form,
            }
            return render(request, 'users/login.html', context)

class ProfileView(LoginRequiredMixin , View):
    def get(self , request):
            context = {
                "user":request.user,
            }
            return  render(request, 'users/profile.html', context)


class LogoutView(LoginRequiredMixin, View):
    def get(self , request):
        logout(request)
        messages.info(request , "You have successfully logged out.")
        return redirect("home_page")


class ProfileUpdateView(LoginRequiredMixin,View):
    def get(self , request):
        user_update_form = ProfileEditForm(instance=request.user)
        context = {
            "form":user_update_form,
        }
        return render(request , 'users/profile_edit.html' , context)

    def post(self , request):
        user_update_form = ProfileEditForm(instance=request.user , data=request.POST , files=request.FILES)
        context = {
            "form":user_update_form,
        }

        if user_update_form.is_valid():
            user_update_form.save()

            messages.success(request , 'You have successfully updated your profile.')

            return redirect('users:profile')

        return render(request , 'users/profile_edit.html' , context)

templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sign In{% endblock %}
{% block content %}
    <div class="row">
        <h2>Sign In</h2>
        <div class="col-4">
            <form method="POST">{% csrf_token %}
                {{ login_form | crispy }}
            <button class="btn btn-outline-success" type="submit">Login</button>
            <span class="ms-3">No account ? Create account <a href="{% url 'users:register' %}">Sign Up</a></span>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}

    <div class="row">
        <div class="col-md-4">
            <img class="profile_photo_style" alt="profile picture" src="{{ user.profile_picture.url }}">
            <h3 class="mt-3">@{{ user.username }}</h3>
        </div>
        <div class="col-md-6">
            <h2 class="mb-4 mt-6">Profile</h2>
            <p class="form-control border-success">Username : {{ user.username }}</p>
            <p class="form-control border-success">First Name : {{ user.first_name }}</p>
            <p class="form-control border-success">Last Name : {{ user.last_name }} </p>
            <p class="form-control border-success">Email : {{ user.email }}</p>
            <p class="form-control border-success">Joined : {{ user.date_joined | date:"M d, Y"}}</p>

            <div class="mt-4">
               <a href="{% url 'books:books_list' %}" class="btn btn-primary">Back</a>
               <a class="btn btn-success" href="{% url 'users:profile_edit' %}">update</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Profile Edit{% endblock %}

{% block content %}
    <div class="row">
        <h2>Profile Edit</h2>
        <div class="col-5">
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form | crispy }}

             <a href="{% url 'users:profile' %}" class="btn btn-primary">Back</a>
            <button type="submit" class="btn btn-outline-success">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Register{% endblock %}
{% block content %}


    <div class="row">
        <h2>Sign Up</h2>
        <div class="col-4">
            <form method="post">{% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-outline-success" type="submit">Sign Up</button>
            </form>
        </div>
    </div>

{% endblock %}